### PR TITLE
feat: add seccomp profile support

### PR DESCRIPTION
**Pull request by eddycharly**
This PR adds seccomp profile support to helm charts.

### CODE REVIEW

**Comment by eddycharly** [comment]
cc @realshuting

**Comment by fjogeleit** [comment]
Thanks for your contribution. I will prepare a release asap

**Comment by eddycharly** [comment]
:+1: 
I bumped the chart version.
I also wrote a quick wrap up here if you're interested https://medium.com/@charled.breteche/kubernetes-security-use-kyverno-policy-reporter-to-fix-kyverno-deployment-22f3bb18540c

**Comment by fjogeleit** [comment]
@eddycharly thats great, thank you a lot!

**Comment by eddycharly** [comment]
Not sure if coverage is expected to fail :thinking:

**Comment by fjogeleit** [comment]
It happens from time to time when it starts the HTTP Server for an API test, I restarted the job.

**Comment by fjogeleit** [comment]
It is released as Helm Chart Version v2.6.0.

**Comment by eddycharly** [comment]
:tada: 
Thank you so much, that was fast !
Gonna update the medium story :)

**Comment by fjogeleit** [comment]
Thanks for your work and contribution

**Pull request merged**
