### PR TITLE
source attribute added to report.

### PR DESCRIPTION
**Pull request by nikolay-o**
Hello @fjogeleit , I want to leverage `source` attribute from `v1alpha.policyReportResult` in reports pushed by policy-reporter. wdyt, is it possible to add this small change to policy reporter?

### CODE REVIEW

**Review by fjogeleit — APPROVED** [review]

**Comment by fjogeleit** [comment]
Hey @nikolay-o, sture - thanks for your contribution

**Comment by nikolay-o** [comment]
Thanks a lot!

**Comment by fjogeleit** [comment]
@nikolay-o sorry for the delay. I released your change today with v2.19.1

**Comment by nikolay-o** [comment]
not a problem, thanks!

**Pull request merged**
