### PR TITLE
Make http port name/number configurable

### PR DESCRIPTION
**Pull request by mortenmj**
This makes it possible to configure the ports that are used by policy reporter and policy reporter kyverno plugin.
As a consequence also making liveness/readiness probes and services more configurable as well.

### CODE REVIEW

**Comment by fjogeleit** [comment]
Hey @mortenmj thanks for your contribution. I think there is one part missing, you have to add the `--port` flag in the policy-reporter deployment like in the kyvernoPlugin deployment. So that the API will be running under the configured port.

**Comment by fjogeleit** [comment]
We may also add new values to also configure the port in the UI subchart because we can not access the values from the main or another subchart directly. It's not ideal but we can add a comment to the port configuration and I also point to this in the documentation otherwise it would not be possible to change the port if you use the UI.

https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/charts/ui/templates/deployment.yaml#L49

something like:

```yaml
policyReporter:
  port: 8080
kyvernoPlugin:
  port: 8080
```

I think that was the main reason why I used fix values for the ports the first time.

**Comment by mortenmj** [comment]
> We may also add new values to also configure the port in the UI subchart because we can not access the values from the main or another subchart directly. It's not ideal but we can add a comment to the port configuration and I also point to this in the documentation otherwise it would not be possible to change the port if you use the UI.

Thanks. I may have a look at that towards the end of next week, unless you have time before that.
I added a commit to set the `--port` flag in the policy-report deployment.

**Comment by fjogeleit** [comment]
Okay, I am at KubeCon this week. So not sure if I find some time for it until next week. You can ignore the lint error. I will update the chart versions before creating the new release.

**Comment by fjogeleit** [comment]
I merged your changes and created a follow PR with the additional UI configuration (#143). The release can take a bit because I am working on additional improvements.

thanks for your contribution

**Pull request merged**
